# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "random"]
# set = true

[config.custom_keywords]
candy_font = "Pacifico"
prog_font = "FiraCode Nerd Font"

[templates.niri]
input_path = "./templates/niri_config.kdl"
output_path = "~/.config/niri/config.kdl"

[templates.ironbar]
input_path = "./templates/colors.css"
output_path = "~/.config/ironbar/colors.css"
post_hook = "ironbar reload"

[templates.rofi]
input_path = "./templates/matugen-rofi.rasi"
output_path = "~/.config/rofi/matugen/matugen-rofi.rasi"

[templates.kitty]
input_path = '~/.config/matugen/templates/matugen_kitty.conf'
output_path = '~/.config/kitty/matugen/colors-matugen.conf'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
