# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "random"]
# set = true

[config.custom_keywords]
candy_font = "Pacifico"
prog_font = "FiraCode Nerd Font"

[templates.niri]
input_path = "./templates/niri_config.kdl"
output_path = "~/.config/niri/config.kdl"

[templates.ironbar]
input_path = "./templates/colors.css"
output_path = "~/.config/ironbar/colors.css"
post_hook = "ironbar load-css ~/.config/ironbar/colors.css"

[templates.rofi]
input_path = "./templates/matugen-rofi.rasi"
output_path = "~/.config/rofi/matugen/matugen-rofi.rasi"
