# theme = "gruvbox_transparent"
theme = "github_dark_transparent"

[editor]
line-number = "relative"
scroll-lines = 1
bufferline = "multiple"
color-modes = true
terminal.command = "kitty"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[keys.normal]
"C-p" = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"'
